spring.application.name=pedido-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=8086

#Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

#Control de loggs
logging.level.root=INFO
logging.level.com.lovable.pedido_service=DEBUG
#Permanencia de Logger
logging.file.name=logs/pedido-service.log

#Microservicios
microservices.usuario.base-url=http://localhost:8087
microservices.producto.base-url=http://localhost:8081

#Perfil Activo
spring.profiles.active=dev








