spring.application.name=boleta-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Esta la puse para coincidir con la guía de Swagger
spring.profiles.active=dev

# 1. Configuración del Puerto
server.port=8084

# 2. Creé una ubicación para guardar una permanencia de los logs
logging.file.name=logs/boleta-service.log

# 3. Configuración de rotación de logs (Buenas prácticas para que el disco no se llene)
# Tamaño máximo por archivo antes de crear uno nuevo
logging.logback.rollingpolicy.max-file-size=10MB
# Total de días que guardará los logs antiguos antes de eliminarlos
logging.logback.rollingpolicy.max-history=7

